#!/usr/bin/env node

'use strict'

// 报错会导致 npm install 失败
process.on('uncaughtException', (err) => {
  console.log(err)
  process.exit(0)
})

const { installFromScripts } = require('elint')
const packageName = process.env.npm_package_name
const packageNameRegexp = /^(@.+\/)?elint-preset-.+/

if (packageName && packageNameRegexp.test(packageName)) {
  installFromScripts(packageName)
}
