#!/usr/bin/env node

'use strict';

const { install } = require('elint');
const packageName = process.env.npm_package_name;

if (packageName && packageName.startsWith('elint-preset')) {
  install(packageName);
}
